name: tfsec

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  tfsec:
    name: Run tfsec static analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        run: tfsec .
